// Code generated by "stringer -type=ArgType"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArgTypeUnknown - -1]
	_ = x[ArgTypeInt16-0]
	_ = x[ArgTypeInt32-1]
	_ = x[ArgTypeInt64-2]
	_ = x[ArgTypeString-3]
	_ = x[ArgTypeBool-4]
	_ = x[ArgTypeBinary-5]
	_ = x[ArgTypeStringList-6]
	_ = x[ArgTypeStringMap-7]
	_ = x[ArgTypeFloat-8]
	_ = x[ArgTypeDouble-9]
	_ = x[ArgTypeBotInfo-10]
	_ = x[ArgTypeIP-11]
	_ = x[ArgTypeURL-12]
	_ = x[ArgTypeDuration-13]
}

const _ArgType_name = "ArgTypeUnknownArgTypeInt16ArgTypeInt32ArgTypeInt64ArgTypeStringArgTypeBoolArgTypeBinaryArgTypeStringListArgTypeStringMapArgTypeFloatArgTypeDoubleArgTypeBotInfoArgTypeIPArgTypeURLArgTypeDuration"

var _ArgType_index = [...]uint8{0, 14, 26, 38, 50, 63, 74, 87, 104, 120, 132, 145, 159, 168, 178, 193}

func (i ArgType) String() string {
	i -= -1
	if i < 0 || i >= ArgType(len(_ArgType_index)-1) {
		return "ArgType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _ArgType_name[_ArgType_index[i]:_ArgType_index[i+1]]
}
