// Code generated by "stringer -type=PacketType"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketTypeHandshake-0]
	_ = x[PacketTypeInfo-1]
	_ = x[PacketTypeRequest-2]
	_ = x[PacketTypeKeepAlive-3]
	_ = x[PacketTypeStartAttack-4]
	_ = x[PacketTypeStopAttack-5]
	_ = x[PacketTypeExecCmd-6]
	_ = x[PacketTypeExecCmdResult-7]
	_ = x[PacketTypeCriticalErrorReport-8]
}

const _PacketType_name = "PacketTypeHandshakePacketTypeInfoPacketTypeRequestPacketTypeKeepAlivePacketTypeStartAttackPacketTypeStopAttackPacketTypeExecCmdPacketTypeExecCmdResultPacketTypeCriticalErrorReport"

var _PacketType_index = [...]uint8{0, 19, 33, 50, 69, 90, 110, 127, 150, 179}

func (i PacketType) String() string {
	if i < 0 || i >= PacketType(len(_PacketType_index)-1) {
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
