// Code generated by "stringer -type=PacketId"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InfectionInformation-0]
	_ = x[AttackStart-1]
	_ = x[Command-2]
	_ = x[CommandResponse-3]
	_ = x[KeepAlive-4]
	_ = x[KeepAliveResponse-5]
}

const _PacketId_name = "InfectionInformationAttackStartCommandCommandResponseKeepAliveKeepAliveResponse"

var _PacketId_index = [...]uint8{0, 20, 31, 38, 53, 62, 79}

func (i PacketId) String() string {
	if i >= PacketId(len(_PacketId_index)-1) {
		return "PacketId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketId_name[_PacketId_index[i]:_PacketId_index[i+1]]
}
